// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlqjFKMhB9vk_ewGjGoUSb4GAY3no8-DQ',
    appId: '1:652819013537:web:b99d169a71623068db35e0',
    messagingSenderId: '652819013537',
    projectId: 'chatbot-769d3',
    authDomain: 'chatbot-769d3.firebaseapp.com',
    storageBucket: 'chatbot-769d3.firebasestorage.app',
    measurementId: 'G-XWSE2BYXJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4wE4jOt8iGir_5-49n2GLdPd_zrTTuNI',
    appId: '1:652819013537:android:0345410db812ef7fdb35e0',
    messagingSenderId: '652819013537',
    projectId: 'chatbot-769d3',
    storageBucket: 'chatbot-769d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi-_0fKgKsraJz0RtkpWezq-TETaGSePM',
    appId: '1:652819013537:ios:9f6946fbed1d06afdb35e0',
    messagingSenderId: '652819013537',
    projectId: 'chatbot-769d3',
    storageBucket: 'chatbot-769d3.firebasestorage.app',
    iosBundleId: 'com.example.financeChatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi-_0fKgKsraJz0RtkpWezq-TETaGSePM',
    appId: '1:652819013537:ios:9f6946fbed1d06afdb35e0',
    messagingSenderId: '652819013537',
    projectId: 'chatbot-769d3',
    storageBucket: 'chatbot-769d3.firebasestorage.app',
    iosBundleId: 'com.example.financeChatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlqjFKMhB9vk_ewGjGoUSb4GAY3no8-DQ',
    appId: '1:652819013537:web:6448cd44ff5d6136db35e0',
    messagingSenderId: '652819013537',
    projectId: 'chatbot-769d3',
    authDomain: 'chatbot-769d3.firebaseapp.com',
    storageBucket: 'chatbot-769d3.firebasestorage.app',
    measurementId: 'G-R6CVG4R46Q',
  );
}
